### ISSUE TITLE
Rerender to fix cdf definition

### ISSUE THREAD

**Issue by blulightspecial** [mids-w203/live-session#4]
@d-alex-hughes can you re-render this, I fixed an error where we called the cdf a cumulative denstiy function instead of a cumulative distribution function, but I don't have bookdown on my machine to do the re-rendering.

**Comment by d-alex-hughes** [comment]
@blulightspecial it should render on ischool.datahub.berkeley.edu. I'm on it right now though, to see if my memory is right.

**Comment by blulightspecial** [comment]
Thanks 🙏 . I will fix it on the datahub in the future.
